spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DATABASE_HOST}:5432/postgres
    username: ${POSTGRES_ROOT_USER}
    password: ${POSTGRES_ROOT_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080